#!/bin/bash
#
# Copyright (C) 2013 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset

read pg_version
read cluster_name
read wal_file

function usage() {
    echo "$0: PG_VERSION CLUSTER_NAME WAL_FILE" >&2
    echo "Example: $0 9.2 main foo" >&2
}

# Check arguments
if [ -z "$pg_version" -o -z "$cluster_name" -o -z "$wal_file" ]
then
    usage
    exit 2
fi

# Check pg_version
if ! echo "$pg_version" | grep -qE "^[0-9]\.[0-9]$"
then
    echo "$0: invalid PG version" >&2
    usage
    exit 2
fi

# Check cluster_name
if ! echo "$cluster_name" | grep -qE "^[a-z]+$"
then
    echo "$0: invalid cluster name" >&2
    usage
    exit 2
fi

# Check wal_file
if ! echo "$wal_file" | grep -qEi "^[A-Z0-9\.]+$"
then
    echo "$0: invalid WAL file name $wal_file" >&2
    usage
    exit 2
fi

file="/var/backups/postgresql-archives/$pg_version/$cluster_name/$wal_file"

if [ ! -f $file ]
then
    echo "$0: no such file or directory $file" >&2
    exit 2
fi

cat $file
