#!/bin/bash
#
# Copyright (C) 2013 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset

tempfile=$(tempfile)

trap "rm -f $tempfile" EXIT HUP INT TRAP TERM ALRM

wal_file=$1
output_file=$2
version=$3
cluster_name=$4
primary=$5

# Start 30 second timeout
sleep 30 && kill -s ALRM $$ &

echo "$version
$cluster_name
$wal_file" | ssh -T $primary | pigz -d > $tempfile

mv $tempfile $output_file
